# vim: ft=dosini

[main]
term = xterm-256color
font=monospace:size=12
dpi-aware = yes
pad = 4x4

[scrollback]
lines = 10000

[mouse]
hide-when-typing = yes

[colors]
# justaguylinux's foot theme
foreground = FFFFFF
#background = 00141d

## Normal colors
regular0 = 1a1a1a  # black
regular1 = ff6b6b  # red
regular2 = a3be8c  # green
regular3 = ffc107  # yellow
regular4 = 80bfff  # blue
regular5 = 9c27b0  # magenta
regular6 = 4fc3f7  # cyan
regular7 = FFFFFF  # white

## Bright colors
bright0 = 808080   # bright black
bright1 = ff8888   # bright red
bright2 = b5d6a0   # bright green
bright3 = ffd54f   # bright yellow
bright4 = a0cfff   # bright blue
bright5 = ba68c8   # bright magenta
bright6 = b3e5fc   # bright cyan
bright7 = FFFFFF   # bright white

## Selection colors
selection-foreground = 00141d
selection-background = b3e5fc
