set runtimepath+=~/.config/vim,~/.config/vim/after
let mapleader =" "

set path+=**

" Nice menu when typing `:find *.py`
set wildmode=longest,list,full
set wildmenu
" Ignore files
set wildignore+=**/node_modules/*
set wildignore+=**/vendor/*
set wildignore+=**/.git/*

call plug#begin("~/.config/vim/plugged")
Plug 'airblade/vim-gitgutter'
Plug 'ap/vim-css-color' " candidate for removal
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'junegunn/goyo.vim'
Plug 'junegunn/gv.vim'
Plug 'junegunn/vim-easy-align'
Plug 'preservim/nerdtree'
Plug 'qpkorr/vim-bufkill'
Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-vinegar'
call plug#end()

set bg=light
let g:goyo_width = 84
" disable error bells
set noeb vb t_vb=
set backupdir=~/.config/vim/backup
set clipboard=unnamed
set directory=~/.config/vim
set fillchars+=vert:│
set incsearch
set laststatus=0
set mouse=a
set nohls
set nowrap
set nu
set scrolloff=8
set shortmess+=c
set showmatch
set signcolumn=number
set splitbelow splitright
set noet
set sw=4
set ts=4
set tw=80
set udf
set udir=~/.config/vim/undo
set updatetime=300
set viminfo="~/.config/vim/viminfo"
au ColorScheme * hi Normal ctermbg=NONE guibg=NONE
au ColorScheme * hi SignColumn cterm=NONE guibg=NONE
au ColorScheme * hi VertSplit ctermbg=NONE guibg=NONE
au ColorScheme * hi ALEErrorSign ctermbg=NONE guibg=NONE
au ColorScheme * hi ALEWarningSign ctermbg=NONE guibg=NONE
au ColorScheme * hi MatchParen ctermbg=black guibg=white
highlight clear SignColumn

" set hyphens as part of the word when working on web files
au! FileType css,html,scss setl iskeyword+=-

au BufReadPost README set filetype=markdown

aug VimDiff
	au!
	au VimEnter,FilterWritePre * if &diff | GitGutterDisable | ALEDisable | endif
aug END

" remove line endings on save
autocmd BufWritePre * :%s/\s\+$//e

" rebinds
" fzf
nmap <Leader>fr :Tags<CR>
nmap <Leader>fa :Files<CR>
nmap <Leader>ff :GFiles<CR>
nmap <Leader>fb :Buffers<CR>

nnoremap <leader>e :NERDTreeToggle<CR>

" Goyo plugin makes text more readable when writing prose:
map <leader>f :Goyo \| highlight clear SignColumn \| set linebreak<CR>
" spell-check set to <leader>o, 'o' for 'orthography':
map <leader>o :setlocal spell! spelllang=en_gb<CR>

" shortcutting split navigation, saving a keypress:
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" replace all is aliased to S.
nnoremap <leader>s :%s//g<Left><Left>
nnoremap Y y$
